name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          cd compiled
          zip ../glassons-scripts.zip *.scpt
          cd ..
          zip -u glassons-scripts.zip RELEASE_README.txt CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: glassons-scripts.zip
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
