name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          zip -r glassons-scripts.zip compiled/ applescripts/ README.md CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            glassons-scripts.zip
            compiled/*.scpt
            applescripts/*.applescript
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
